version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: sec-demo-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:80}
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${BACKEND_URL:-http://localhost:3001}
    container_name: sec-demo-frontend
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://backend:3001}
    depends_on:
      - backend
    restart: unless-stopped