version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: sec-demo-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: sec-demo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped